### ISSUE TITLE
Implementation details for AutoML

### ISSUE THREAD

**Issue by chenkaiyu1997** [fastnlp/fastNLP#101]
关于fastNLP的AutoML有几个问题：

1. 我现在是想AutoML作为一个fastNLP.models里的model，并且调用AutoModel.fit的时候，不用正常的trainer，而是用AutoML的trainer去train这个model。所以我主要在Trainer里面新加一个AutoMLTrainerClass，Model里面加一个AutoMLModel的class，这样可以吧？

2. 如果采取添加model和trainer的实现，如何改变Dataset的处理方式呢？比如搜索是否添加CharLevelFeatures，ParsingFeatures和其他文本级别的Features？

3. 如果用户只需要fastNLP.FastNLP.fit(X_data_file, Y_data_file)，这样是不是对用户更友好一点？但这样是否与fastNLP主框架不很兼容？

4. AutoKeras的整体设计主要是BayesianOptimization去搜CNN结构，而我们的是不是要搜索更多？包括超参搜索，是否添加Char特征和其他Parsing特征等，选取利用哪些预训练模型和向量，选择怎样的CNN/LSTM/Transformer/CRF结构和层次等等。我们的AutoML是不是都应该搜索，才能保证AutoML的可用性？

**Comment by FengZiYjun** [comment]
1. 这样是可以的。当然，也可以将AutoML的东西集中起来，例如fastNLP.automl。这个要具体实现才知道，怎么方便怎么来。
2. 进行AutoML时数据应该是确定的，特征不会改变。DataSet有哪些特征是由对应的DataSetLoader决定的，而DataSetLoader是跟train和model无关的。所以目前在AutoMLTrainerClass里改变DataSet可能不好做。
3. 这样做的前提是X_data_file和Y_data_file已经预处理好了。如果把预处理的结果存下来，应该也可以做到。
4. 数据特征是确定的，所以是否添加某种feature应该不在搜索范围内。其他的都可以作为搜索的对象，但重要性可以排个序，优先实现比较重要的。

这样的理解有没有问题？  @xpqiu

**Comment by xpqiu** [comment]
1. trainer可以另外再写一个。当然也可以考虑作为一个单独的和fastNLP并列的项目。
4. Feature是需要支持搜索的，如果fastNLP不支持，可以考虑修改fastNLP接口。

**Comment by FengZiYjun** [comment]
那么我们需要给DataSet设计一个便于添加特征的接口

**Comment by chenkaiyu1997** [comment]
Features搜索也需要的话，那我就更倾向于直接FastNLP.AutoML.fit()吧？

关于要搜索哪些Feature，有什么论文可以看看，关于更全面说明哪些NLP Features的？
