### ISSUE TITLE
trainner 对2维数据的传入问题

### ISSUE THREAD

**Issue by Explorerhpx** [fastnlp/fastNLP#119]
**problem**
我的input是二维矩阵，一列代表1句话，一个矩阵代表一篇文章，我在文章层面做过padding（把不同长度的句子扩展成同样长度的向量），但是因为不同文章的句子数以及最长句子的长度不同，所以不同文章的2维表示的size是不同的，这就需要在传入一个batch的数据时对这个batch里的所有二维向量进行padding。但fastnlp的trainner似乎现在还没有支持这种操作。

**Bug**
我在调试的过程中发现，Trainner调用forward后，传入的数据不是一个3维矩阵，而是一个2维矩阵，准确的说总是只会传入一篇文章的2句话

**Desktop**
 - OS: Windows10 CPU
 - numpy: 1.14.2

**Comment by hazelnutsgz** [comment]
Have you ever checked the parameter **batch_size** when initializing the **Trainer**?

**Comment by FengZiYjun** [comment]
现在暂不支持二维padding，但你可以手动处理

**Comment by Explorerhpx** [comment]
> Have you ever checked the parameter **batch_size** when initializing the **Trainer**?

I have set the parameter **batch_size = 16** when I use Trainer

**Comment by Explorerhpx** [comment]
> 现在暂不支持二维padding，但你可以手动处理

好的，谢谢回复

**Comment by FengZiYjun** [comment]
最新发布的v0.3.1已经支持自定义padding方法，见教程 https://github.com/fastnlp/fastNLP/blob/master/tutorials/fastNLP_padding_tutorial.ipynb
