### ISSUE TITLE
masked_fill bug in star-transformer！

### ISSUE THREAD

**Issue by wlhgtc** [fastnlp/fastNLP#138]
If you use masked_fill according to ex_mask (0 for pad), it will fill not padding position(which value in ex_mask is 1) with 0, this will lead a bad performance.

https://github.com/fastnlp/fastNLP/blob/master/fastNLP/modules/encoder/star_transformer.py#L59-L66

@FengZiYjun

**Comment by wlhgtc** [comment]
fix in #137

**Comment by choosewhatulike** [comment]
fixed.
