### ISSUE TITLE
star-transformer何时可以放出完整代码？实验完全无法重现，SST-5数据集上相差6个点哦

### ISSUE THREAD

**Issue by michael-wzhu** [fastnlp/fastNLP#148]
**Describe the bug** 
清晰而简要地描述bug

**To Reproduce**
使用你们的star-transformer代码，然后用allennlp做训练(glove 42B 词向量)， 最后结果见如图，与论文中报告的结果相差6个点。

请求解释！以及完整版的代码，就是可以完全复现结果的完整版。

**Additional context**
备注
![image](https://user-images.githubusercontent.com/35124505/58102859-986d4980-7c14-11e9-8a78-132563006690.png)

**Comment by choosewhatulike** [comment]
我们还在使用FastNLP积极复现实验，代码不久就会放出。
当前的结果可以在这里看到 https://github.com/fastnlp/fastNLP/blob/dev0.4.0/reproduction/README.md
你可以调节模型的初始化，学习率，dropout等参数，看看结果有没有改善哦。

**Comment by michael-wzhu** [comment]
请问在SST-5上面的实验，使用的是8k的整句句子数据，还是15w+的包含不完整句子情感标签的？

**Comment by choosewhatulike** [comment]
用了不完整句子做训练，但测试只使用完整的句子。
你可以使用以下代码获取训练和测试数据。
``` python
from fastNLP.io import SSTLoader
train_data = SSTLoader(subtree=True, fine_grained=True).load('path')
test_data = SSTLoader(subtree=False, fine_grained=True).load('path')
```

**Comment by Jackie127** [comment]
能给出star_transformer分类的具体例子吗？例子中能顺便给出数据格式吗

**Comment by speedcell4** [comment]
@michael-wzhu 请问你复现成功了么

**Comment by michael-wzhu** [comment]
并没有

**Comment by speedcell4** [comment]
我也是, 我自己写的和直接复制的他的都没跑出论文里的分数

**Comment by xpqiu** [comment]
这里的版本是fastnlp小组的复现。我已经让一作来check了，会尽快完善。

**Comment by xpqiu** [comment]
@michael-wzhu @Jackie127 @speedcell4 见上面PR，我们会在fastnlp 0.5版本正式更新。

**Comment by michael-wzhu** [comment]
Thank you, Prof Qiu, for the fast response and continued attention. i will try it as soon as i get some free time. Thank you!
