### ISSUE TITLE
ModuleNotFoundError:

### ISSUE THREAD

**Issue by fdcck** [fastnlp/fastNLP#150]
我在使用fastnlp时，先import的时候会报错，没找到原因.
下面的是 我在本地运行 advance_tutorial的报错结果
请问是什么原因呀？
//fastnlp的版本为最新版0.4.0

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-658aea032ffd> in <module>
      1 # 声明部件
      2 import torch
----> 3 import fastNLP
      4 from fastNLP import DataSet
      5 from fastNLP import Instance

d:\program\python\python3.7\lib\site-packages\fastNLP\__init__.py in <module>
     56 
     57 from .core import *
---> 58 from . import models
     59 from . import modules

d:\program\python\python3.7\lib\site-packages\fastNLP\models\__init__.py in <module>
     25 ]
     26 
---> 27 from .base_model import BaseModel
     28 from .bert import BertForMultipleChoice, BertForQuestionAnswering, BertForSequenceClassification, \
     29     BertForTokenClassification

d:\program\python\python3.7\lib\site-packages\fastNLP\models\base_model.py in <module>
      1 import torch
      2 
----> 3 from ..modules.decoder.mlp import MLP
      4 
      5 

d:\program\python\python3.7\lib\site-packages\fastNLP\modules\__init__.py in <module>
     48 
     49 from . import aggregator
---> 50 from . import decoder
     51 from . import encoder
     52 from .aggregator import *

d:\program\python\python3.7\lib\site-packages\fastNLP\modules\decoder\__init__.py in <module>
      6 ]
      7 
----> 8 from .crf import ConditionalRandomField
      9 from .mlp import MLP
     10 from .utils import viterbi_decode

ModuleNotFoundError: No module named 'fastNLP.modules.decoder.crf'

**Comment by fdcck** [comment]
另外，我刚刚试了一下，旧版本无此问题

**Comment by xuyige** [comment]
由于打包上传到pip的时候出现了错误，所以有这个问题
这在0.4.1版本当中已经被修复，请及时更新

**Comment by WillQvQ** [comment]
感谢您的反馈，这个问题在0.4.1版本中已经被修复，请及时更新.
