### ISSUE TITLE
请问现在支持加载Elmo模型到序列标注任务中吗？

### ISSUE THREAD

**Issue by Wanjun0511** [fastnlp/fastNLP#151]
请问现在支持加载Elmo模型到序列标注任务中吗？可以的话是否有example参考，没有的话是否在计划中。多谢！

**Comment by xuyige** [comment]
现在对于预训练的embedding没有支持elmo，只支持了glove。
你可以把elmo写进模型里面，或者调用allennlp的接口把词向量算好之后直接扔进模型里面也是可以的

**Comment by xuyige** [comment]
elmo按照目前的更新计划的话应该在下一个大版本（0.5.0）更新出来

**Comment by Wanjun0511** [comment]
@xuyige  allennlp的接口只支持带char_cnn的elmo模型，对中文语料不支持。后续更新的话能否解决一下这个问题，多谢！

**Comment by xuyige** [comment]
> @xuyige allennlp的接口只支持带char_cnn的elmo模型，对中文语料不支持。后续更新的话能否解决一下这个问题，多谢！

你是希望能够用elmo模型来自己重新训练一个语言模型吗？还是只单纯的希望使用allennlp给出的编码结果？

**Comment by Wanjun0511** [comment]
@xuyige 我是希望能用elmo训练中文语料下的语言模型，并基于这个模型去做中文语料的序列标注任务。

**Comment by yhcc** [comment]
我们尝试了使用中文语料基于笔画和汉字做ELMO的预训练，但效果不是很理想。
