### ISSUE TITLE
fastNLP安装完成之后导入有错

### ISSUE THREAD

**Issue by lovelyvivi** [fastnlp/fastNLP#160]
Python 3.5环境下安装fastNLP，显示可以安装成功，但是import fastNLP时会出现
  File "D:\anaconda\lib\site-packages\fastNLP\core\instance.py", line 40
    f" type={(str(type(self.fields[field_name]))).split(s)[1]}" for field_name in self.fields) + "}"
                                                              ^
SyntaxError: invalid syntax
Python3.6和Python3.7也不行，都是安装完成之后，import时就会报错

**Comment by yhcc** [comment]
3.5不支持，因为3.5不支持通过f-string来进行format输出。但是在我们的开发人员的window上3.6是可以运行的。你确认使用的是3.6的python吗？

**Comment by lovelyvivi** [comment]
是的呢，我之前使用的是3.6版本的Python，也不可以，找不出原因来，今天我在Python3.7上也试过了，依旧是不行






------------------ 原始邮件 ------------------
发件人: "yhcc"<notifications@github.com>;
发送时间: 2019年6月4日(星期二) 晚上8:11
收件人: "fastnlp/fastNLP"<fastNLP@noreply.github.com>;
抄送: "冰雨"<782199724@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fastnlp/fastNLP] fastNLP安装完成之后导入有错 (#160)




3.5不支持，因为3.5不支持通过f-string来进行format输出。但是在我们的开发人员的window上3.6是可以运行的。你确认使用的是3.6的python吗？

**Comment by yhcc** [comment]
也是报相同的错误吗？你的系统是哪个版本的？

**Comment by lovelyvivi** [comment]
我是win10系统，要不我加一下您好友？我主要想复现一下金字塔卷积神经网络，我看小姐姐的代码很简单，我也想用一下这个模块






------------------ 原始邮件 ------------------
发件人: "yhcc"<notifications@github.com>;
发送时间: 2019年6月4日(星期二) 晚上8:14
收件人: "fastnlp/fastNLP"<fastNLP@noreply.github.com>;
抄送: "冰雨"<782199724@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fastnlp/fastNLP] fastNLP安装完成之后导入有错 (#160)




也是报相同的错误吗？你的系统是哪个版本的？

**Comment by xuyige** [comment]
> 我是win10系统，要不我加一下您好友？我主要想复现一下金字塔卷积神经网络，我看小姐姐的代码很简单，我也想用一下这个模块
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "yhcc"<notifications@github.com>; 发送时间: 2019年6月4日(星期二) 晚上8:14 收件人: "fastnlp/fastNLP"<fastNLP@noreply.github.com>; 抄送: "冰雨"<782199724@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [fastnlp/fastNLP] fastNLP安装完成之后导入有错 (#160) 也是报相同的错误吗？你的系统是哪个版本的？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

你的python3.6跟3.7的时候报的是什么错呢？

**Comment by lovelyvivi** [comment]
因为我现在用的是3.5，之前3.6报错我给卸载了，重新装成3.5的，所以报错情况没有截图






------------------ 原始邮件 ------------------
发件人: "Yige XU"<notifications@github.com>;
发送时间: 2019年6月4日(星期二) 晚上8:19
收件人: "fastnlp/fastNLP"<fastNLP@noreply.github.com>;
抄送: "冰雨"<782199724@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fastnlp/fastNLP] fastNLP安装完成之后导入有错 (#160)



 
我是win10系统，要不我加一下您好友？我主要想复现一下金字塔卷积神经网络，我看小姐姐的代码很简单，我也想用一下这个模块
 …
 ------------------ 原始邮件 ------------------ 发件人: "yhcc"notifications@github.com; 发送时间: 2019年6月4日(星期二) 晚上8:14 收件人: "fastnlp/fastNLP"fastNLP@noreply.github.com; 抄送: "冰雨"782199724@qq.com;"Author"author@noreply.github.com; 主题: Re: [fastnlp/fastNLP] fastNLP安装完成之后导入有错 (#160) 也是报相同的错误吗？你的系统是哪个版本的？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
你的python3.6跟3.7的时候报的是什么错呢？

**Comment by yhcc** [comment]
你有在某个课程群里吗？你可以在群里直接加我

**Comment by lovelyvivi** [comment]
不好意思，貌似我不在您说的那些课程群了，我QQ782199724,或者您可以跟我说下您QQ，我来加你






------------------ 原始邮件 ------------------
发件人: "yhcc"<notifications@github.com>;
发送时间: 2019年6月4日(星期二) 晚上8:21
收件人: "fastnlp/fastNLP"<fastNLP@noreply.github.com>;
抄送: "冰雨"<782199724@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fastnlp/fastNLP] fastNLP安装完成之后导入有错 (#160)




你有在某个课程群里吗？你可以在群里直接加我
