### ISSUE TITLE
请问下现在支持多任务学习么？分类+序列标注的joint-model

### ISSUE THREAD

**Issue by qichaotang** [fastnlp/fastNLP#162]

**Comment by xuyige** [comment]
multi-task的trainer跟现在单一任务的trainer在逻辑上存在一定的差异性，需要重新写一个trainer。现在的fastNLP暂时不支持这种multi-task的模型。或者看看您的模型是否能做成类似single-task的模型呢？

**Comment by qichaotang** [comment]
好吧！sad，那你们这个有开发指南么？

**Comment by xpqiu** [comment]
欢迎你开发一个multitask的trainer：）
