### ISSUE TITLE
关于 fastNLP.modules.ConvMaxpool 中 padding 使用的疑问？

### ISSUE THREAD

**Issue by qichaotang** [fastnlp/fastNLP#164]
参考link:https://fastnlp.readthedocs.io/zh/latest/fastNLP.modules.html#fastNLP.modules.ConvMaxpool

<img width="772" alt="屏幕快照 2019-06-11 下午8 22 17" src="https://user-images.githubusercontent.com/12878507/59271804-17d7c100-8c87-11e9-894c-55f8ccb73b5a.png">

**Comment by qichaotang** [comment]
看见 pytorch Conv1D 文档里面也没说 所有 kernel 都是共享一个 padding，比如 kernel_sizes = (2, 3, 4, 5), out_channels = (500, 400, 300, 200), padding = (1, 2, 3, 4) 应该可以这样设置才对吧？

**Comment by yhcc** [comment]
感谢，我昨天也发现那个地方有点问题，我们最近会在dev0.5.0推出补丁。补丁版本不允许拥有偶数的kernel_size, padding会根据kernel_size自动调整以使得每种kernel的output是一样的shape。

**Comment by qichaotang** [comment]
赞，期待，之前看到一个库里面是pad大小自动设置为 (kernel_size - 1) / 2，自己在本地就直接改了
