### ISSUE TITLE
关于fastNLP.core.batch模块中关于多进程prefetch疑问

### ISSUE THREAD

**Issue by zwkatgithub** [fastnlp/fastNLP#170]
阅读core/batch.py源代码时遇到一些疑问，希望能解答。

在batch.py代码中设置了全局变量_python_is_exit并且使用atexit进行了注册，但是在多进程程序当中，子进程只是复制父进程的全局变量的值，也就是在父进程(或子进程)中修改全局变量不会改变子进程(或父进程)的值，也就是全局变量不能使进程间通信，即使使用atexit进行注册，也只是局限于当前进程中。
在静态方法_run_fetch中，有一个逻辑是：当队列Full之后，判断_python_is_exit为真就返回None，我的问题是，既然_python_is_exit在程序退出之前无法手动修改，也就是_python_is_exit一直为False，那么这个逻辑在什么情况下会触发？

**Comment by choosewhatulike** [comment]
这个确实存在问题，因为python的多进程并不会共享全局变量。后续我们将采用Pytorch中的多进程DataLoader来优化我们的batch，具体代码可以看dev0.5.0分支。
