### ISSUE TITLE
调用模型STSeqLabel参数不对

### ISSUE THREAD

**Issue by mandobango** [fastnlp/fastNLP#189]
**调用README里面Usage下面的实例代码出现报错**
   model = STSeqLabel(vocab_size=10000, num_cls=50, emb_dim=300)
报错：TypeError: __init__() got an unexpected keyword argument 'vocab_size'
有人遇到同样的问题吗，怎么解决呢？

**Comment by xuyige** [comment]
> **调用README里面Usage下面的实例代码出现报错**
> model = STSeqLabel(vocab_size=10000, num_cls=50, emb_dim=300)
> 报错：TypeError: **init**() got an unexpected keyword argument 'vocab_size'
> 有人遇到同样的问题吗，怎么解决呢？

Star-Transformer的代码在最新的版本当中已经做了修改，我们将在今明两天发布更新，请留意

**Comment by xuyige** [comment]
#193 
最新的Star-Transformer已经发布了，可以参考里面的内容
