### ISSUE TITLE
Source code for Style transformer

### ISSUE THREAD

**Issue by nctubuddy** [fastnlp/fastNLP#195]
**Is your feature request related to a problem? Please describe.**
Hi, it was mentioned in https://arxiv.org/abs/1905.05621 that the source code will be made available some time in the future. Is there a timeline for the release?

**Describe the solution you'd like**
I am interested in seeing the released code so that I could do some experiments with it.

**Describe alternatives you've considered**

**Additional context**
The paper was accepted to the up coming ACL 2019. Will we be able to see the code before the event? Thanks a lot.

**Comment by xuyige** [comment]
> **Is your feature request related to a problem? Please describe.**
> Hi, it was mentioned in https://arxiv.org/abs/1905.05621 that the source code will be made available some time in the future. Is there a timeline for the release?
> 
> **Describe the solution you'd like**
> I am interested in seeing the released code so that I could do some experiments with it.
> 
> **Describe alternatives you've considered**
> 
> **Additional context**
> The paper was accepted to the up coming ACL 2019. Will we be able to see the code before the event? Thanks a lot.

Thank you for your issue.
The source code of Style Transformer with fastNLP is not ready yet. You can send an e-mail to the first author for original code.

**Comment by xpqiu** [comment]
The location of style transformer is here: https://github.com/fastnlp/style-transformer
