### ISSUE TITLE
Could you provide README files in English, too?

### ISSUE THREAD

**Issue by hyeseonko** [fastnlp/fastNLP#196]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yhcc** [comment]
Thanks for your interest in our project, and I am sorry that the language stops you from using this tool. Although we want to provide an English version of documents and tutorials, recently we do not have enough time. We will definitely fill in English documents and tutorials in future.
