### ISSUE TITLE
dataset类中的delete_instance方法报错

### ISSUE THREAD

**Issue by MeloMing** [fastnlp/fastNLP#197]
`from fastNLP import DataSet`
`dataset = DataSet({'a': list(range(-5, 5))})`
`dataset.delete_instance(3)`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-be7c4657c670> in <module>
      1 from fastNLP import DataSet
      2 dataset = DataSet({'a': list(range(-5, 5))})
----> 3 dataset.delete_instance(3)

~/anaconda3/envs/fastnlp/lib/python3.6/site-packages/fastNLP/core/dataset.py in delete_instance(self, index)
    482         else:
    483             for field in self.field_arrays.values():
--> 484                 field.pop(index)
    485 
    486     def delete_field(self, field_name):

AttributeError: 'FieldArray' object has no attribute 'pop'

**Comment by yhcc** [comment]
是的，这里有问题，我们会在近期代码中修改这个问题，感谢。
