### ISSUE TITLE
[Feature request ][question]如何自定义分词器/如何显式使用spacy分词

### ISSUE THREAD

**Issue by chizhu** [fastnlp/fastNLP#198]
感谢你们团队的努力，fastnlp非常棒。这里，我有个问题。
可以看出你们很大程度也是借鉴了pytorchtext库，我看到你们依赖库里也是有spacy库，那么在分词这块，fastnlp怎么显式使用spacy,希望给个示例。

**Comment by yhcc** [comment]
好像spacy不能处理中文分词吧？我们稍后给你提供一个jieba或者其它分词工具的参考示例吧。

**Comment by yhcc** [comment]
这里我就随便举个例子吧
from fastNLP import DataSet
import jieba
from fastNLP import Instance

# 我这里创建一个dataset说明以下怎么用，但实际使用的时候可能是读取进来的
dataset = DataSet()
dataset.append(Instance(raw_chars='今天的天气好热。'))
dataset.append(Instance(raw_chars='已经好多天没有下雨了。'))
print(dataset)

# 分词就在这一步进行
dataset.apply_field(lambda raw_chars: jieba.lcut(raw_chars) ,field_name='raw_chars', new_field_name='raw_words')
print(dataset)

# 第一个print的输出
DataSet({'raw_chars': 今天的天气好热。 type=str},
{'raw_chars': 已经好多天没有下雨了。 type=str})
# 第二个print的输出，有一列List的raw_words
DataSet({'raw_chars': 今天的天气好热。 type=str,
'raw_words': ['今天', '的', '天气', '好', '热', '。'] type=list},
{'raw_chars': 已经好多天没有下雨了。 type=str,
'raw_words': ['已经', '好多天', '没有', '下雨', '了', '。'] type=list})

**Comment by chizhu** [comment]
感谢您的解答。也就是分词都要人工做，最后都要自己转变为list才能index化。

**Comment by xpqiu** [comment]
以后fastnlp会提供自己的分词工具

**Comment by chizhu** [comment]
感谢邱老师的解答，期待后续版本。fastnlp真的很棒，文档很清晰，注释很良心。哈哈！
ps:pytorch-transformers更新到1.0了  bert/gpt2/xlnet一个模板复用，可以跟进一波了。

**Comment by xuyige** [comment]
> 感谢邱老师的解答，期待后续版本。fastnlp真的很棒，文档很清晰，注释很良心。哈哈！
> ps:pytorch-transformers更新到1.0了 bert/gpt2/xlnet一个模板复用，可以跟进一波了。

bert已经加入fastNLP里面了，xlnet正在跟进当中
