### ISSUE TITLE
有没有可能加入分布式训练

### ISSUE THREAD

**Issue by mikomou** [fastnlp/fastNLP#200]
目前指定多个GPU训练时，模型会被封装如pytorch的DataParallel，是否可以加入选择DistributedDataParallel来封装。

**Comment by xuyige** [comment]
> 目前指定多个GPU训练时，模型会被封装如pytorch的DataParallel，是否可以加入选择DistributedDataParallel来封装。

dev0.5.0已经加入并在测试当中

**Comment by xuyige** [comment]
在0.5.0及以后的版本当中，可以使用DistTrainer来进行分布式训练
具体参见 https://github.com/fastnlp/fastNLP/blob/master/fastNLP/core/dist_trainer.py
