### ISSUE TITLE
What's the status of AutoML in this project?

### ISSUE THREAD

**Issue by threefoldo** [fastnlp/fastNLP#201]
I didn't find related code in master branch, nor discussions about it.

AutoML is new to me, it sounds complicated. Have you ever considered using something simpler? For example: https://github.com/hyperopt/hyperopt

**Comment by yhcc** [comment]
感谢你的关注。但我们最近还没来得及开发AutoML的相关功能。我们也在考虑如何结合hyperopt到fastNLP中使得调超参数的过程更加友好一点。

**Comment by threefoldo** [comment]
Thank you.
