### ISSUE TITLE
CNN文本分类器的几个小问题

### ISSUE THREAD

**Issue by lintongmao** [fastnlp/fastNLP#206]
这个模型是Yoon Kim, 2014的经典模型，我观察到docstring和签名中有这样几个问题：
- [ ] 参数列表：['init_embed', 'num_classes', '**kernel_nums**=(3, 4, 5)', 'kernel_sizes=(3, 4, 5)', 'padding=0', 'dropout=0.5']，这里的`kernel_nums`在下面的docstring中是`out_channels`，私以为直接改成`out_channels`比较直观；
- [ ] 上面这个`out_channels`的**默认值**，在实现中用的是`(3,4,5)`，在Kim的论文中是**各100个feature maps**；
- [ ] Kim的模型一般约定俗成地叫做TextCNN，但是在fastnlp中被命名为`CNNText`，不知道是不是有其他考量。

**Comment by xpqiu** [comment]
这个不是严格的follow，你可以实现一个严格版本。另外你发现不对的地方可以直接改，然后pr过来，在dev0.5的分支上改。

**Comment by xpqiu** [comment]
还有一些模型在这里：https://github.com/fastnlp/fastNLP/tree/dev0.5.0/reproduction/text_classification/model

**Comment by lintongmao** [comment]
> 这个不是严格的follow，你可以实现一个严格版本。另外你发现不对的地方可以直接改，然后pr过来，在dev0.5的分支上改。

好的，我原本觉得先有一个heads-up会比较好。
