### ISSUE TITLE
Star-Transformer的位置编码没有生效？

### ISSUE THREAD

**Issue by qratosone** [fastnlp/fastNLP#238]
**Describe the bug** 
https://github.com/fastnlp/fastNLP/blob/master/fastNLP/modules/encoder/star_transformer.py
代码第71行开始：
```python
        if self.pos_emb and False:
            P = self.pos_emb(torch.arange(L, dtype=torch.long, device=embs.device) \
                             .view(1, L)).permute(0, 2, 1).contiguous()[:, :, :, None]  # 1 H L 1
            embs = embs + P
```
后面那个`and False:`岂不是意味着`pos_emb`永远都不会生效？

**Comment by choosewhatulike** [comment]
做文本分类时，position embedding的影响不大，所以这里可以去掉。后续我们会加上选择要不要加position embedding 的选项。
