### ISSUE TITLE
模型预测问题

### ISSUE THREAD

**Issue by binzhouchn** [fastnlp/fastNLP#239]
训练完模型后比如分类模型，怎么预测？直接model.predict有点麻烦啊

**Comment by binzhouchn** [comment]
还有分类预测的时候，能不能再给出预测出最佳类别的概率值

**Comment by yhcc** [comment]
现在fastNLP还没有提供直接能够从raw data到类别的预测；关于你说得最佳类别的概率这个，你在模型的forward中不要直接输出argmax之后的结果，而是输出类别的概率就可以找到对应的概率值。
