### ISSUE TITLE
fastnlp跑分类问题有类似算F1的函数么

### ISSUE THREAD

**Issue by binzhouchn** [fastnlp/fastNLP#244]
fastnlp跑分类问题有类似算F1的函数么， SpanFPreRecMetric貌似只有NER的时候能用

**Comment by xuyige** [comment]
在最新的开发分支dev0.5.0当中已经增加了这样的功能，进一步测试后很快会合并到master分支当中
具体内容参见
https://github.com/fastnlp/fastNLP/blob/dev0.5.0/fastNLP/core/metrics.py#L381
