### ISSUE TITLE
logger模块

### ISSUE THREAD

**Issue by q759729997** [fastnlp/fastNLP#247]
**Describe the bug**
logger模块，设置日志级别不起作用.

**To Reproduce**
1. 代码

~~~
from fastNLP import logger

print('设置前：logger.level:{}'.format(logger.level))
logger.debug('level设置前，测试 debug 打印效果')
logger.setLevel('DEBUG')
print('设置后：logger.level:{}'.format(logger.level))
logger.debug('level设置后，测试 debug 打印效果')
~~~

2. 结果

~~~
设置前：logger.level:20
设置后：logger.level:10
~~~

**Expected behavior**

1. 希望日志级别、日志格式、日志输出位置可以自由定义。
2. 希望可以增加一些该部分说明。

**Desktop (please complete the following information):**
 - OS: win10
 - Version 0.5.0

**Comment by choosewhatulike** [comment]
谢谢反馈。我们发现这是因为 logger 使用 logging handler 来打印消息，只有消息的level高于logger's level & logger.handlers' level, 消息才会输出。可以参考[stackoverflow](https://stackoverflow.com/questions/11111064/how-to-set-different-levels-for-different-python-log-handlers).
#### Solution
建议将`logger.level`设置为1，然后使用`logger.add_file() or logger.set_stdout()`设置handlers‘ level。
Try this:
``` python
from fastNLP import logger
logger.setLevel(1) #set logger to lowest level

logger.debug('level设置前，测试 debug 打印效果') # before 
logger.set_stdout(level='DEBUG')
logger.debug('level设置后，测试 debug 打印效果') # after
```

#### Further More
关于你提的几个问题: 
- logger是基于python logging 模块封装的，你可以参考使用方式设置日志级别，可以使用数字，常用的DEBUG=10，INFO=20，与logging模块相同。至于自定义输出格式，我们会考虑加入这个功能，现阶段可以参考logging，添加自定格式的handler到logger。
- 可以使用 `logger.add_file(path, level)` 增加日志输出到文件的handler。
- 可以使用 `logger.set_stdout('none')` 关闭命令行的输出。
- 关于logger的文档和说明，我们会尽快补上。
