### ISSUE TITLE
Tester缺少明细信息

### ISSUE THREAD

**Issue by q759729997** [fastnlp/fastNLP#249]
**Is your feature request related to a problem? Please describe.**  问题是什么
Tester缺少明细信息

**Describe the solution you'd like** 解决方案是什么
Tester中建议增加明细信息显示。
如：分类增加各个类别的指标；NER增加各个实体类别的指标。

**Additional context** 备注
明细信息可以更方便分析试验结果。

**Comment by yhcc** [comment]
SpanFPreRecMetric有一个only_gross参数，将它置为True可以看到每个label的F1。
ClassifyFPreRecMetric是用于计算分类F1的，可以看到不同class的F1。
不同类别的准确率我们还需要更新一下代码才能支持
