### ISSUE TITLE
Trainer保存模型的功能建议

### ISSUE THREAD

**Issue by q759729997** [fastnlp/fastNLP#250]
**Is your feature request related to a problem? Please describe.**  问题是什么
1、Trainer中_save_model虽然已经预留了only_param参数，但是Trainer初始化时并不能配置。pytorch是建议保存param的。希望可以考虑此部分的修改。

**Comment by yhcc** [comment]
你好，感谢你的建议。目前这个需求可以通过使用SaveModelCallback实现。
