### ISSUE TITLE
关于文本摘要NYT50数据集疑问

### ISSUE THREAD

**Issue by staer-tan** [fastnlp/fastNLP#251]
有看到你们的文本摘要的论文中给出了关于NYT50的结果，也展开了实验。请问这个数据集是如何获取的呢？

**Comment by maszhongming** [comment]
我们的数据集从以下链接获得：http://nlp.cs.berkeley.edu/projects/summarizer.shtml

**Comment by Devin100086** [comment]
请问现在还能否获取NYT50数据集，目前貌似对应网站已经无法正常获取对应数据集了

**Comment by korokes** [comment]
> 请问现在还能否获取NYT50数据集，目前貌似对应网站已经无法正常获取对应数据集了

老哥，有数据集的获取方式吗，同求~
