### ISSUE TITLE
load_data中词向量加载方法

### ISSUE THREAD

**Issue by QY-AI** [fastnlp/fastNLP#253]
请问在fastNLP/reproduction/sequence_labelling/chinese_ner/LatticeLSTM/ 项目中的load_data.py中88行 pretrained_embedding = load_word_emb(embedding_path, 300, vocab)中的load_word_emb使用的是哪里的方法，提示找不到。

**Comment by xuyige** [comment]
感谢您的issue
非常抱歉这里的代码使用的是旧版本的函数，在最新版本当中同样功能的函数位于fastNLP/fastNLP/io/embed_loader.py的第43行，具体参见
https://github.com/fastnlp/fastNLP/blob/master/fastNLP/io/embed_loader.py#L43

**Comment by actforjason** [comment]
def load_with_vocab(embed_filepath, vocab, dtype=np.float32, padding='<pad>', unknown='<unk>', normalize=True,
`load_word_emb(embedding_path, 300, vocab)` 300怎么办，对应什么？

**Comment by yhcc** [comment]
把300直接扔掉吧，300本来是申明维度的，但是由于可以直接从加载的embedding中推断，所以就可以不需要这个维度了。
