### ISSUE TITLE
encoder模块DotAttention类中softmax的bug

### ISSUE THREAD

**Issue by keezen** [fastnlp/fastNLP#254]
https://github.com/fastnlp/fastNLP/blob/980aba9898d2c33689b88ad41f9cf173ef9e2e31/fastNLP/modules/encoder/attention.py#L29

此处应为`dim=-1`，否则在四维情况下就是错误的

@xuyige @choosewhatulike @yhcc

**Comment by xuyige** [comment]
这里一般来说作为Transformer的DotAttention大部分情况应该是三维张量。后续会修改为-1
