### ISSUE TITLE
数据是否能分批读取

### ISSUE THREAD

**Issue by ZhaoyueSun** [fastnlp/fastNLP#255]
目前似乎是在DataLoader中一次性把所有数据加载到内存中，可能出现内存不够得情况，是否有工具能分批读取，或者其他的解决建议？

**Comment by xuyige** [comment]
感谢您的issue
由于分批读取数据在构建DataSet、词表等方面与目前的架构存在一定的不兼容，因此目前fastNLP不支持分批读取数据的功能。
对于大数据集个人建议使用内存更大的服务器或者使用预设词表然后分批加载数据分批训练

**Comment by yhcc** [comment]
主要原因在于，根据我们很多实际使用经验来看，很多时候nlp面临的问题不是数据太大(除了预训练任务)，而是数据太少。所以我们对数据scalable这一块没有花太多精力～
