### ISSUE TITLE
Default value for train args.

### ISSUE THREAD

**Issue by keezen** [fastnlp/fastNLP#26]
https://github.com/fastnlp/fastNLP/blob/8a87807274735046a48be8eb4b1ca10801875039/fastNLP/core/trainer.py#L42-L45

Should we set some default value for train_args? Otherwise we will pass all these args every time, which is very redundant.

**Comment by xuyige** [comment]
i think we should set some default value
if user need to change the default value, they can pass their own args

**Comment by FengZiYjun** [comment]
I deleted the default value in trainer. One reason is that those are important arguments that I want users to set them explicitly, otherwise ValueError will remind users. Another reason is that I want the definition of trainers clean and concise, without if-else statements. 
However, one possible solution is to pre-define those default value in **train_args**, rather than in trainers.

**Comment by choosewhatulike** [comment]
We can have a default .cfg file to be loaded before the user defined .cfg in the ConfigLoader. So user can easily check what kind of args that have default, and can overwrite them by writing these args in there .cfg

**Comment by xuyige** [comment]
so different trainer should use different default values? maybe we can provide the default value what we suggest
if the user forget load train_args or set values from train_args, should we remind them?

**Comment by choosewhatulike** [comment]
> so different trainer should use different default values?
maybe we need that, and even for different model we have different default values.
> if the user forget load train_args or set values from train_args, should we remind them?
I think we can set as many default args as we could, let user to run the code instantly without setting anything.

**Comment by xpqiu** [comment]
For the long-term goal,  we wish that the users may build their models without considering their hyperparameters, like AutoML.

Current, it's better to reduce the user's efforts. 
Consider this, a dictionary of args with default value is preferred. But I suggest to put these args in formal args list directly. Thus, the user can easily know which argument has what default value. 

Besides, the following codes are somewhat redundant and fragile.
`
        self.n_epochs = train_args["epochs"]
        self.batch_size = train_args["batch_size"]
        self.pickle_path = train_args["pickle_path"]

        self.validate = train_args["validate"]
        self.save_best_dev = train_args["save_best_dev"]
        self.model_saved_path = train_args["model_saved_path"]
        self.use_cuda = train_args["use_cuda"]
`

**Comment by choosewhatulike** [comment]
I would say we could pass args like:
``` python
    # a trainer method need args to pass
    def __int__(self, epochs, batch_size, validate, save_best_dev, use_cuda)
          pass
    
# pass args
train_args = ConfigLoad.load() # load from cfg file
Trainer(**train_args)
```
So we can know the args without look into the method body, and write the default cfg file. user also can set there own args changing default values
