### ISSUE TITLE
希望增加seq2seq模型，以及BLEU、ROUGE等评估方法，谢谢

### ISSUE THREAD

**Issue by 18222278799** [fastnlp/fastNLP#260]
**Is your feature request related to a problem? Please describe.**  问题是什么

**Describe the solution you'd like** 解决方案是什么

**Describe alternatives you've considered** 其他解决方案

**Additional context** 备注

**Comment by xuyige** [comment]
您好，感谢您的issue
seq2seq跟BLEU在计划当中，ROUGE因为涉及到比较复杂的环境配置问题，我们在reproduction里面提供了一个近似估计的metric，详情见 https://github.com/fastnlp/fastNLP/blob/master/reproduction/Summarization/README.md
