### ISSUE TITLE
Tester的model说不是module是orderedDict

### ISSUE THREAD

**Issue by 18222278799** [fastnlp/fastNLP#261]
您好，在我运行下面代码时，tester不好用，您知道是什么原因么

if(args.train):
trainer.train()
saver = ModelSaver("./cache/model_ckpt_100.pkl")
saver.save_pytorch(model,param_only=False)

if(args.predict):
model=ModelLoader.load_pytorch_model("./cache/model_ckpt_100.pkl")
tester = Tester(datasets['test'], model, batch_size=args.test_batch, metrics=metrics)
tester.test()

But it has error, which said TypeError: The type of model must be 'torch.nn.Module', got '<class'collections.OrderedDict'>'
谢谢

**Comment by 18222278799** [comment]
您好，我已经解决了，是因为我在saver.save_pytorch(model)没有加param_only=False，因为默认是true，我想问一下作者，如果只保存参数，应该怎么用tester调用呢，谢谢

**Comment by yhcc** [comment]
需要先初始化一个model，使用model.load_state_dict函数加载保存的权重，再传入Tester
