### ISSUE TITLE
您好，怎么进行inference呢

### ISSUE THREAD

**Issue by 18222278799** [fastnlp/fastNLP#262]
您好，怎么进行前向呢，因为只有tester的功能，如果给一个未标注的句子，怎么进行前向，输出标注结果，谢谢。

**Comment by xuyige** [comment]
您好，感谢您的issue
在fastNLP当中我们提供了一个Predictor，具体见https://github.com/fastnlp/fastNLP/blob/master/fastNLP/core/predictor.py

**Comment by 18222278799** [comment]
您好，使用这个函数，必须保证新的数据集dataset中包含所有field么，那这样需要重新load数据，并且重新给字词进行index排序吧，是不是有点复杂了，有什么简单的方式么。不是直接放进去输入自己进行操作么

**Comment by yhcc** [comment]
目前对inference的支持不太完善。需要自己对新load的数据进行预处理，index等。

**Comment by onebula** [comment]
Predictor 里的batch_size 是1，GPU环境下应该会有不少性能损失，建议暴露该参数
