### ISSUE TITLE
Proposal to abolish the use of dictionary as argument passed to trainer

### ISSUE THREAD

**Issue by JerrikEph** [fastnlp/fastNLP#27]
https://github.com/fastnlp/fastNLP/blob/8a87807274735046a48be8eb4b1ca10801875039/fastNLP/core/trainer.py#L27

To make code more consistent, and debuggable. I propose we abolish the use of dictionary as argument passed to trainer class. instead we can use `**kwargs` instead, with argument checking. Default values of argument can be stored in a template dictionary.

```python
def foo(**kwargs):

    tmplt = {'arg1': 'value1', 'arg2': 'value2', 'arg3': 'value3', 'arg4': 'value4', 'arg5': 'value5'}
    for k in kwargs:
        if k not in tmplt:
            raise ValueError('Argument error: %s'%k)
        if type(tmplt[k]) != type(kwargs[k]):
            raise ValueError('Argument %s type mismatch: expected %s while get %s' %
                             (k, type(tmplt[k]), type(kwargs[k])))
        tmplt[k] = kwargs[k]
    print(tmplt)
```
When called,
```python
foo(arg1='hello', arg3='there')

foo(arg1='hello', arg_error='there')

foo(arg1='hello', arg3=1)
```
The corresponding results would be,

```
{'arg1': 'hello', 'arg2': 'value2', 'arg3': 'there', 'arg4': 'value4', 'arg5': 'value5'}
```

The second calling is passed with a false argument name,
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    foo(arg1='hello', arg_error='there')
  File "test.py", line 6, in foo
    raise ValueError('Argument error: %s'%k)
ValueError: Argument error: arg_error
```
The third calling is passed with right argument name `arg3` but with wrong type of content `<integer>`
```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    foo(arg1='hello', arg3=1)
  File "test.py", line 9, in foo
    (k, type(tmplt[k]), type(kwargs[k])))
ValueError: Argument arg3 type mismatch: expected <type 'str'> while get <type 'int'>
```

User will know exactly what's going on when passed with a wrong argument name or a wrong argument type.
And from a users' perspective, it makes user code more consistent and elegant.

**Comment by keezen** [comment]
A considerable solution.

**Comment by xuyige** [comment]
but we need to check the argument name and argument type every time we call the function.
an other point, will pycharm (or maybe other ide?), remind the argument name to users while they are coding?

**Comment by FengZiYjun** [comment]
@JerrikEph Thanks for suggestions. `kwargs` is good for readability, but it introduces more coding. 
1. Most arguments passed to Trainer are loaded as a `ConfigSection` from a config file. The `ConfigSection` class has the same interface as a dict. 
```
train_args = ConfigSection()
ConfigLoader.load(train_args)
trainer.train(train_args)
```
Every time a new setting is added in the config file, you don't need to modify the interface of trainer.train. 
But if we use `trainer.train(epoch=train_args.epoch, save_model=train_args.save_model, ...)`, a new argument has to be added by hand. 

2. Trainer has sub-classes. Some sub-class may have more specific arguments. If all arguments are explicitly passed, `trainer.train` will be very long. This looks ugly. 

3. As I suggest in another issue, if we want default value for Trainer, we shall specify those default value in `ConfigSection`. This gives both Trainer more freedom and users convenience.

**Comment by JerrikEph** [comment]
@FengZiYjun 
There are ways to pass a dictionary to **kwargs:
```
arg_dict = {'arg1': 'hello', 'arg3': 'there'}
foo(**arg_dict)
```

The main concern here is debugability, when user mess up such as passing a wrong key-valued dictionary to the trainer,  the error could be confusing. that would be head-scratching for user to debug what have gone wrong.

**Comment by xpqiu** [comment]
I suggest to pass the args like Keras.

def fit(self,
            x=None,
            y=None,
            batch_size=None,
            epochs=1,
            verbose=1,
            callbacks=None,
            validation_split=0.,
            validation_data=None,
            shuffle=True,
            class_weight=None,
            sample_weight=None,
            initial_epoch=0,
            steps_per_epoch=None,
            validation_steps=None,
            **kwargs):
        """Trains the model for a given number of epochs (iterations on a dataset).
