### ISSUE TITLE
运行tutorial时报错CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by jwc19890114** [fastnlp/fastNLP#282]
在尝试运行文本分类教程“https://fastnlp.readthedocs.io/zh/latest/tutorials/%E6%96%87%E6%9C%AC%E5%88%86%E7%B1%BB.html”的时候报错，在其他程序中验证过GPU可以使用GPU加速，但是这里会完成一个epoch之后报CUDA error: unspecified launch failure。
求助，谢谢

**Comment by WillQvQ** [comment]
你好~请问可以提供一下显卡配置和更多的报错信息吗？我们测试了几次没有遇到这个问题。我搜索了一些资料，这个问题可能是由显卡导致的。

**Comment by jwc19890114** [comment]
> 你好~请问可以提供一下显卡配置和更多的报错信息吗？我们测试了几次没有遇到这个问题。我搜索了一些资料，这个问题可能是由显卡导致的。

谢谢，我把pytorch重新降到1.2之后没有这个问题了，困扰了一上午，谢谢

**Comment by WillQvQ** [comment]
遇到类似问题的用户可以持续关注这个连接 https://github.com/pytorch/pytorch/issues/27837 。目前，PyTorch 1.3, 1.4 对部分显卡的支持不太好。我们手上的显卡种类有限，无法覆盖到所有类型的显卡，非常抱歉。

**Comment by jwc19890114** [comment]
> 遇到类似问题的用户可以持续关注这个连接 [pytorch/pytorch#27837](https://github.com/pytorch/pytorch/issues/27837) 。目前，PyTorch 1.3, 1.4 对部分显卡的支持不太好。我们手上的显卡种类有限，无法覆盖到所有类型的显卡，非常抱歉。

感谢回复~
