### ISSUE TITLE
自定义模型时如何处理多输入的情况

### ISSUE THREAD

**Issue by onebula** [fastnlp/fastNLP#284]
fastNLP.core.const 中提到dataset的field命名方式，具有多列words时，依次使用words1, words2, 具有多列chars时，依次使用chars1， chars2 ，……，我理解是fastNLP可以通过这些预设的字段名找到相应的特征。但是doc里没讲怎么组织模型的多输入，例如既有多个words，又有多个seq_len，那么forward函数就会包含多个输入变量，这些输入变量是怎么对应到dataset的field的？是相同的变量名么？还是有某种固定的顺序呢？同样的，自定义多输出的情况该如何处理呢？

**Comment by yhcc** [comment]
fastNLP是通过变量名匹配field的，假设Model的forward参数为

**Comment by onebula** [comment]
明白了，谢谢
