### ISSUE TITLE
建议在训练过程中打印所指定的多个指标的值

### ISSUE THREAD

**Issue by onebula** [fastnlp/fastNLP#288]
trainer中支持通过列表传入多个metric，训练时以第一个metric为准。但是实际运行中仅打印了第一个metric，剩下的metric没有打印。希望能够同时打印所有的metric。
我在做多任务学习的过程中遇到了这个问题，每个任务有一个指标。由于需要调整多任务的超参数配置及权重，因此需要通过观察各个任务的metric判断各个任务的收敛速度。

**Comment by yhcc** [comment]
按道理，是都会打印的。建议尝试通过pip install git+https://github.com/fastnlp/fastNLP安装github上的版本试一下。

**Comment by onebula** [comment]
有更新pypi源的版本的计划么？

**Comment by yhcc** [comment]
月底应该就会更新

**Comment by onebula** [comment]
> 按道理，是都会打印的。建议尝试通过pip install git+[https://github.com/fastnlp/fastNLP安装github上的版本试一下。](https://github.com/fastnlp/fastNLP%E5%AE%89%E8%A3%85github%E4%B8%8A%E7%9A%84%E7%89%88%E6%9C%AC%E8%AF%95%E4%B8%80%E4%B8%8B%E3%80%82)

我找到问题了，我使用了多个acc，但是没有通过set_metric_name设置为不同的名字，而评估返回的结果是字典，这些acc的值全部填入了同一个键“acc”中，由于只有一个键，最终只打印了这个键的值。
希望能够在文档里做一些提示，或者代码里能自动检查重名的metric，并修改名字为“acc_1”，”acc_2“这样的（keras有类似功能）
