### ISSUE TITLE
embeding 数据无法自动下载

### ISSUE THREAD

**Issue by Thornhill-GYL** [fastnlp/fastNLP#289]
请问一下，提供embeding模型的服务器212.129.155.247是否还在运行，每次尝试连接，都提示连接拒绝，另外，embeding模型可否由自己提供？

**Comment by yhcc** [comment]
现在已经恢复了，不好意思。也可以用自己的embeding模型的。

**Comment by Thornhill-GYL** [comment]
好的，十分感谢
