### ISSUE TITLE
指代消解API的入口

### ISSUE THREAD

**Issue by baozi-lala** [fastnlp/fastNLP#294]
如果需要使用指代消解，需要用到哪个函数，可以给一个demo吗

**Comment by yhcc** [comment]
抱歉，我们现在还没提供指代消解的函数和模型。 https://github.com/fastnlp/fastNLP/tree/master/reproduction/coreference_resolution 这里有一份指代消解的复现供你参考，不过也是无法直接用来进行指代消解的。
