### ISSUE TITLE
OSError: [E050] Can't find model 'en'

### ISSUE THREAD

**Issue by laomagic** [fastnlp/fastNLP#295]
from fastNLP.io import SST2Pipe
pipe=SST2Pipe()
出现错误：
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by choosewhatulike** [comment]
可能是spacy找不到模型，请下载试试。
```
python -m spacy download en
```

**Comment by jwc19890114** [comment]
> 可能是spacy找不到模型，请下载试试。
> 
> ```
> python -m spacy download en
> ```

这类分词模型需要单独下载
