### ISSUE TITLE
Tester能否返回测试集的预测结果

### ISSUE THREAD

**Issue by onebula** [fastnlp/fastNLP#296]
测试集比较大的情况下，Tester跑完一遍只得到了metrics，为了得到预测结果还需要用Predictor再跑一遍，非常费时间。建议Tester也同时返回预测结果

**Comment by yhcc** [comment]
主要是预测结果这事儿还挺麻烦的，因为不同的model如何组装预测结果（例如可能涉及到去除padding这样）有点差别，所以我们目前对预测结果这块支持本身也不太好。你说的这个建议，我们之后对predictor再做一些升级后再考虑如何结合一下吧，谢谢～

**Comment by jwc19890114** [comment]
> 主要是预测结果这事儿还挺麻烦的，因为不同的model如何组装预测结果（例如可能涉及到去除padding这样）有点差别，所以我们目前对预测结果这块支持本身也不太好。你说的这个建议，我们之后对predictor再做一些升级后再考虑如何结合一下吧，谢谢～

额，如果想加载训练好的模型预测一批新数据呢，好像没有找到加载模型的load方法
