### ISSUE TITLE
BertSum的数据格式

### ISSUE THREAD

**Issue by Wang-Yufei** [fastnlp/fastNLP#299]
您好！
请问summarization里面的bertsum，需要什么格式的数据呢？有例子参考嘛

**Comment by WillQvQ** [comment]
你好！您的问题可以参考 [论文原作者的 Github](https://github.com/nlpyang/BertSum)。目前您看到的 reproduction 是去年的版本，对应旧版的 fastNLP，不能直接使用。我们会在1个月内将其更新到与当前版本fastNLP匹配的版本，并会在更新的第一时间通知您。

您也可以关注我们组的其它摘要模型[HeterSumGraph](https://github.com/brxx122/HeterSumGraph) , [MatchSum](https://github.com/maszhongming/MatchSum) 和 [Effective_Extractive_Summarization](https://github.com/maszhongming/Effective_Extractive_Summarization)
