### ISSUE TITLE
[咨询]请问有多标签文本分类的demo吗？

### ISSUE THREAD

**Issue by unstory** [fastnlp/fastNLP#307]
**Is your feature request related to a problem? Please describe.**  问题是什么
看了文档：https://fastnlp.readthedocs.io/zh/latest/ ，目前没有看到多标签文本分类的例子，请问有文本多标签文本分类的例子吗？

**Describe the solution you'd like** 解决方案是什么

**Describe alternatives you've considered** 其他解决方案

**Additional context** 备注

**Comment by yhcc** [comment]
我们暂时还没有，之后我们考虑补充一下吧。如果你有遇到特定的困难，我们也可以一起帮你看下。

**Comment by MrRace** [comment]
@yhcc  请问现在有多标签分类的example吗？

**Comment by yhcc** [comment]
目前还没有，我们考虑加一下
