### ISSUE TITLE
ELMO预训练模型下载问题咨询

### ISSUE THREAD

**Issue by superwars** [fastnlp/fastNLP#308]
![image](https://user-images.githubusercontent.com/53506929/85836100-aeaae900-b7c8-11ea-9f8e-6a1b5027eeea.png)
我使用fastNLP教程当中的ELMO的例子，但是出现了如下的问题：

`requests.exceptions.ProxyError: HTTPConnectionPool(host='10.141.250.66', port=8123): Max retries exceeded with url: http://212.129.155.247/embedding/elmo_en_Small.zip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc6b93baa90>: Failed to establish a new connection: [Errno 110] Connection timed out',)))
`

这是网络的原因吗？

**Comment by yhcc** [comment]
应该是诶。尝试直接访问http://212.129.155.247/embedding/elmo_en_Small.zip下载，然后解压这个文件，把model_dir_or_name修改为这个解压后的文件夹路径应该就可以了。
