### ISSUE TITLE
默认validate_every=-1不是每个epoch才会执行验证测试吗？ 为什么训练了10%就验证了？

### ISSUE THREAD

**Issue by renyuxiang** [fastnlp/fastNLP#328]
Epoch 1/10:  10%|█▍            | 300/3000 [00:17<02:26, 18.39it/s, loss:0.35327]
  0%|                                                    | 0/38 [00:00<?, ?it/s]
Test:   0%|                                              | 0/38 [00:00<?, ?it/s]
Test:  16%|██████                                | 6/38 [00:00<00:00, 58.39it/s]
Test:  34%|████████████▋                        | 13/38 [00:00<00:00, 58.59it/s]
Test:  47%|█████████████████▌                   | 18/38 [00:00<00:00, 54.57it/s]
Test:  61%|██████████████████████▍              | 23/38 [00:00<00:00, 51.14it/s]
Test:  76%|████████████████████████████▏        | 29/38 [00:00<00:00, 53.01it/s]
Test:  95%|███████████████████████████████████  | 36/38 [00:00<00:00, 55.98it/s]
Evaluate data in 0.68 seconds!
Evaluation on dev at Epoch 1/10. Step:300/3000: 
AccuracyMetric: acc=0.838333

**Comment by renyuxiang** [comment]
用官方教程https://fastnlp.readthedocs.io/zh/latest/tutorials/%E6%96%87%E6%9C%AC%E5%88%86%E7%B1%BB.html，为什么这样？

**Comment by yhcc** [comment]
这个10%是指所有的训练过程的10%（一共循环10个epoch，10%的时候刚好是一个epoch结束）
