### ISSUE TITLE
刚开始使用fastNlp得embedding功能，运行示例代码出现问题

### ISSUE THREAD

**Issue by Magic-123** [fastnlp/fastNLP#335]
![image](https://user-images.githubusercontent.com/53642108/97850454-05a06c00-1d2f-11eb-887e-6042f13108e9.png)
1.使用fastNlp（v0.5.5）提供的示例代码，下载语言模型没有问题，但是出现如下错误
![image](https://user-images.githubusercontent.com/53642108/97850796-79427900-1d2f-11eb-938f-bdce3e71afb4.png)
2.随后使用文档提供的“cn-base"模型，代码如下：
![image](https://user-images.githubusercontent.com/53642108/97850939-ab53db00-1d2f-11eb-8c1c-94dd853a6eb7.png)
语言模型无法自动下载，出现错误如下：
![image](https://user-images.githubusercontent.com/53642108/97851022-c45c8c00-1d2f-11eb-8e09-117c8bcac811.png)

**Comment by xuyige** [comment]
1. 这个错误的是由于PyTorch版本升级带来的变动而导致的，在github的最新版本当中已经修复了这个问题，我们将在下一个版本发布这个修复。可以先
`pip uninstall fastNLP`
之后，再
`pip install git+https://github.com/fastnlp/fastNLP.git`
来安装最新版本
2. `cn-base`模型是BERT里面的一个模型，需要用BertEmbedding来调用。StaticEmbedding只能调用类似word2vec或者是glove的静态embedding。在文档当中有详细分类说明。

**Comment by Magic-123** [comment]
好的，谢谢，解决了
