### ISSUE TITLE
Can't find model 'en'

### ISSUE THREAD

**Issue by Styx-TZ** [fastnlp/fastNLP#341]
使用YelpFullPipe出现的报错。
将源码 classification.py中131行改为         super().__init__(lower=lower, tokenizer=tokenizer, lang='en_core_web_sm')
utils.py中第83行改为        if lang != 'en_core_web_sm':
即可正常运行。
其它pipe中也存在类似问题，建议处理一下lang='en'和lang='en_core_web_sm'，增加健壮性。

**Comment by xuyige** [comment]
感谢您的issue，这个原因可能是因为spacy的版本升级导致的，我们将在下个版本对此进行修复
