### ISSUE TITLE
fastnlp是否提供增量训练的接口

### ISSUE THREAD

**Issue by Elegenthus** [fastnlp/fastNLP#342]
您好！请问fastnlp的fastNLP.core.trainer是否是增量训练的接口？
也就是说，如果我传入Trainer的model不是一个初始化的神经网络模型，而是一个曾经训练过的带有参数的神经网络模型，想用新的数据再训练给这个模型，这样的方式fastnlp.Trainer是支持的嘛？

**Comment by yhcc** [comment]
可以的，Trainer只是一个训练迭代过程，不区分模型是否已经训练过。

**Comment by Elegenthus** [comment]
好的，感谢！
