### ISSUE TITLE
未能按预期设置Padder

### ISSUE THREAD

**Issue by LouChao98** [fastnlp/fastNLP#355]
**Describe the bug** 
此issue包含两个问题
1. 根据文档，`DataSet.add_field(..., padder=None)`应该禁用`padder`。 但是`DataSet.add_field`内部调用`FieldArray.__init__`时，`padder=None` 会导致自动创建一个`AutoPadder()`。和文档描述不一致。
2. `DataSet._add_apply_field` 时，如果`new_field_name in self.field_arrays`, 即inplace操作，应当保留`padder`属性不变，但实际`padder`被重置为`AutoPadder`。

**To Reproduce**
* 针对问题1
```
ds = DataSet()
ds.add_field('idx', [1, 2, 3], padder=None)
print(ds['idx'].padder)  # should be None, but AutoPadder
```
* 针对问题2
```
ds = DataSet()
ds.add_field('idx', [1, 2, 3])
ds['idx'].set_padder(None)  # workaround of problem 1
print(ds['idx'].padder)
ds.apply_field(lambda x: x, 'idx', 'idx')
print(ds['idx'].padder)  # should be None, but AutoPadder
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Python: 3.8.8
 - Version: latest (pip install git+https://github.com/fastnlp/fastNLP.git, 2021.3.29)

**Comment by yhcc** [comment]
感谢您的细心。我们已经修复了这个bug。但由于最初设计的原因，当前状态下如果您不希望fastNLP对某个field进行pad，直接通过set_ignore_type()函数来让fastNLP不要去check这个field的类型并不对它进行pad。
