### ISSUE TITLE
Release Trained model in coreference_resolution （关于指代消解训练模型）

### ISSUE THREAD

**Issue by Ricardokevins** [fastnlp/fastNLP#356]
Interesting Work. And I`d like to know can you release the trained model parameter which can be useful in other downsteam NLP task. 
很有意思的工作，请问一下可以公开训练后的模型参数吗，以便于在下游任务中直接作为输入

**Comment by yhcc** [comment]
做这个模型的同学毕业了，所以模型权重也没有了。之后我们如果实现了更新的coreference model的话，我们应该会放出权重的。
