### ISSUE TITLE
序列标准怎样使用训练好的模型进行结果预测

### ISSUE THREAD

**Issue by zxjlm** [fastnlp/fastNLP#368]
如题, 请问有没有办法像spacy那样, 直接输入一条语句, 然后输出结果中将语句中的实体标注出来.

或者有没有其他的办法达成类似的输入输出效果?

**Comment by yhcc** [comment]
目前还没有办法达到这个，需要自己实现这种功能。

**Comment by xpqiu** [comment]
对标spacy的是fastHan，https://github.com/fastnlp/fastHan
fastHan中提供这种功能。

**Comment by zxjlm** [comment]
好的，最近也在看fastHan， 感谢回复。
