### ISSUE TITLE
the core module reports an error

### ISSUE THREAD

**Issue by CoderBinGe** [fastnlp/fastNLP#394]
My fastnlp = 0.7.1, torch =1.10.0+cu113，I don’t know why the following error was reported, Please help to take a look!

![image](https://user-images.githubusercontent.com/26380524/140901045-7f7e7ddb-f37e-4d24-ae20-fabacbb98dcd.png)

**Comment by yhcc** [comment]
Why did the error say "MyTrainer" object has no attribute, should it be Trainer object? I tried to reproduce the error, but my code work properly, can you try to first uninstall fastNLP ``pip uninstall fastNLP``  then install by ``pip install git+https://github.com/fastnlp/fastNLP@dev``.

**Comment by CoderBinGe** [comment]
> Why did the error say "MyTrainer" object has no attribute, should it be Trainer object? I tried to reproduce the error, but my code work properly, can you try to first uninstall fastNLP `pip uninstall fastNLP` then install by `pip install git+https://github.com/fastnlp/fastNLP@dev`.

Yes, MyTrainer inherits from fastNLP Trainer. I'll try to check the code again and again. Thank you for the reply.
