### ISSUE TITLE
措辞建议on arxiv https://arxiv.org/abs/1902.09113

### ISSUE THREAD

**Issue by shouldsee** [fastnlp/fastNLP#408]
Star Transformer: https://arxiv.org/abs/1902.09113

preprint里面对于connection分为了radical和ring.

个人建议,不应该使用radical描述此种拓扑. radical意思是自由基,极端的, 比如 radical nationalist意思是极端民族主义

建议替换成radial,表明是径向的作用量.

感谢分享你们的工作!

**Comment by yhcc** [comment]
感谢您的建议，我们已经更新了arxiv上的paper。
