### ISSUE TITLE
fastNLP.io.OntoNotesNERLoader 无法使用

### ISSUE THREAD

**Issue by Nero0017** [fastnlp/fastNLP#411]
![image](https://user-images.githubusercontent.com/67811893/165899036-274c742b-4170-4ea7-b0b6-b28caa3ebd5a.png)
![image](https://user-images.githubusercontent.com/67811893/165899113-5164e589-8afb-4aad-9e90-60cfdc6585ed.png)
![image](https://user-images.githubusercontent.com/67811893/165899146-81d74d7a-56d1-4df8-85da-3e844e459bb7.png)

请问这种情况应该怎么解决？

**Comment by yhcc** [comment]
data_bundle = fastNLP.io.OntoNotesNERLoader().load(base_dir)，错误原因是由于OntoNotesNERLoader没有实例化。

**Comment by yhcc** [comment]
- [ ]
