### ISSUE TITLE
HTTPError occurred while downloading embedding vector 'en-glove-840b-300d'

### ISSUE THREAD

**Issue by PhSe-coder** [fastnlp/fastNLP#423]
Got error message while running following code from [Part II: 使用预训练的静态embedding](https://fastnlp.readthedocs.io/zh/latest/tutorials/tutorial_3_embedding.html#part-ii-embedding)
```python
import torch
from fastNLP.embeddings import StaticEmbedding
from fastNLP import Vocabulary

vocab = Vocabulary()
vocab.add_word_lst("this is a demo .".split())

embed = StaticEmbedding(vocab, model_dir_or_name='en-glove-840b-300d')

words = torch.LongTensor([[vocab.to_index(word) for word in "this is a demo .".split()]])  # 将文本转为index
print(embed(words).size())  # StaticEmbedding的使用和pytorch的nn.Embedding是类似的
```
**Error message**:
> HTTPError: Status code:404. Fail to download from http://download.fastnlp.top/embedding/glove.840B.300d.zip.

**Comment by yhcc** [comment]
请到https://nlp.stanford.edu/projects/glove/这个网址下载，或者使用https://nlp.stanford.edu/data/glove.840B.300d.zip直接下载。
