### ISSUE TITLE
[文档疑似错误]

### ISSUE THREAD

**Issue by iamqiz** [fastnlp/fastNLP#428]
**Describe the bug** 
T1. dataset 和 vocabulary 的基本使用 — fastNLP 1.0.0-beta 文档
http://www.fastnlp.top/docs/fastNLP/master/tutorials/basic/fastnlp_tutorial_1.html
![Snipaste_2022-11-10_13-14-41](https://user-images.githubusercontent.com/48077521/201006496-1c92f1f0-a194-441f-b727-ae4d288b1ed0.png)

**Comment by yhcc** [comment]
感谢，这里确实是写错了～
