### ISSUE TITLE
Should add the code for generating pre-trained embedding? or leave it to user?

### ISSUE THREAD

**Issue by keezen** [fastnlp/fastNLP#57]
https://github.com/fastnlp/fastNLP/blob/961a321712dc2b6458c8b5e49c9aa383b96f841e/fastNLP/loader/embed_loader.py#L4-L8

the embedding loader and processing has not been implemented yet
@FengZiYjun @choosewhatulike @xuyige @xpqiu

**Comment by FengZiYjun** [comment]
In `CWS+POS tag interface #54` pull request, I forget to mention the changes in `embed_loader.py`.
A method called `load_embedding` is added to load pre-trained embedding, extract word embedding, and combine with other random embedding.
https://github.com/fastnlp/fastNLP/blob/31eac4a795f90e87bfe5cff2df87eadeceffd688/fastNLP/loader/embed_loader.py#L16

**Comment by FengZiYjun** [comment]
@choosewhatulike 
Our discussion last time should lead to the solution of this issue.
