### ISSUE TITLE
A proposal for path join.

### ISSUE THREAD

**Issue by keezen** [fastnlp/fastNLP#58]
https://github.com/fastnlp/fastNLP/blob/961a321712dc2b6458c8b5e49c9aa383b96f841e/fastNLP/core/trainer.py#L292

Maybe it will be better to use `os.path.join(self.pickle_path, model_name)`, which is more robust.

For example, `os.path.join('save', 'a.txt')` and `os.path.join('save/', 'a.txt')` both return `save/a.txt`, while `'save' + 'a.txt'` returns `'savea.txt'`, which is not expected.

**Comment by FengZiYjun** [comment]
agree. Most codes are for quick prototyping. Any improvements are welcome.

**Comment by xuyige** [comment]
i also agree.

**Comment by FengZiYjun** [comment]
Fixed in a recent issue. Closed.
