### ISSUE TITLE
A warning from torch about LSTM

### ISSUE THREAD

**Issue by FengZiYjun** [fastnlp/fastNLP#75]
`UserWarning: ONNX export failed on LSTM because batch_first not supported`
It happens when sequence labeling models are used.
I can't find any solution to this warning.

**Comment by xpqiu** [comment]
@yhcc

**Comment by FengZiYjun** [comment]
@yhcc 
To reproduce this warning:
1. checkout branch `add_field_support`
2. run  fastNLP/test/model/seq_labeling.py
