### ISSUE TITLE
We shouldn't share the vocabulary for word and label.

### ISSUE THREAD

**Issue by xpqiu** [fastnlp/fastNLP#78]
**Describe the bug** 
清晰而简要地描述bug

We shouldn't share the vocabulary for word and label.

[https://github.com/fastnlp/fastNLP/blob/82502aa67d6a2ab1c30edae5bec06ff92f8b3ee8/fastNLP/core/preprocess.py#L242](https://github.com/fastnlp/fastNLP/blob/82502aa67d6a2ab1c30edae5bec06ff92f8b3ee8/fastNLP/core/preprocess.py#L242)

**Comment by FengZiYjun** [comment]
This is solved by introducing Vocabulary class.
Only in the vocabulary of a sequence data has default value, such as padding, unknown labels.
