### ISSUE TITLE
Proposal changes of class names

### ISSUE THREAD

**Issue by FengZiYjun** [fastnlp/fastNLP#83]
Since we don't have sub classes in trainer, tester and preprocessor, there is no need to call them a base class.
```
BaseTrainer ----> Trainer
BaseTester  ----> Tester
BaseProprocess ----> Preprocess
```

**Comment by xpqiu** [comment]
Agree.

**Comment by xpqiu** [comment]
Suggest making 'preprocess' as a method of class Dataset.  The methods 'save' and 'load' of Preprocess are also extracted to be the methods of Dataset.

**Comment by FengZiYjun** [comment]
Names have changed in pull request #86
