### ISSUE TITLE
two bugs,

### ISSUE THREAD

**Issue by 2017alan** [fastnlp/fastNLP#84]
**Describe the bug** 
[epoch:   1 step: 15623] train loss:  1.4 time: 0:16:43
[epoch:   1 step: 15624] train loss:  1.4 time: 0:16:43
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    trainer.train(model,train_data , dev_data)
  File "/home/sjwang/anaconda3/lib/python3.6/site-packages/fastNLP/core/trainer.py", line 142, in train
    if self.save_best_dev and self.best_eval_result(validator):
  File "/home/sjwang/anaconda3/lib/python3.6/site-packages/fastNLP/core/trainer.py", line 373, in best_eval_result
    _, _, accuracy = validator.metrics()
  File "/home/sjwang/anaconda3/lib/python3.6/site-packages/fastNLP/core/tester.py", line 254, in metrics
    y_prob, y_true = zip(*self.eval_history)
ValueError: not enough values to unpack (expected 2, got 0)

**when i test the self attention model, i meat this bug. that is during the test ,it want to compare the current test accuracy with the history accuracy ,however the history list is empty. i have already set save_output = true  and   save_loss = true .**

the second bug  is during the initial process , the config_loader tell me 
"cannot load attribute epochs in section train" ,in my config file there is a line "epoches = 30" .
and the program will not break down for this line,and it will run two epochs before run the test module.

**Comment by FengZiYjun** [comment]
I am afraid you used the very old codes. Recommend to switch to the latest.

**Comment by 2017alan** [comment]
yes, my version is  out of date. 
and i find in the  module/decoder/MLP.py file ,the MLP class must choose a activation function ,i guess maybe we should add an option   **not add any activation function**.

**Comment by FengZiYjun** [comment]
@2017alan 
somthing was wrong with the backprop. please check the loss.
