### ISSUE TITLE
Proposal for a concise data flow

### ISSUE THREAD

**Issue by xpqiu** [fastnlp/fastNLP#85]
A concise data flow:
dataset.loadCoNLL()   %load data from raw text.
dataset.preprocess()   %
train,test=dataset.split()  %optional for the data without dev set.   This feature should extract the split from preprocess.
dataset.save_to_pickle() % 
dataset.load_from_pickle() % load the preprocess data.

%codes for model construction
model.fit(train hyperparameter)
model.evaulate(test)

@FengZiYjun

**Comment by FengZiYjun** [comment]
@choosewhatulike @keezen @xuyige @JerrikEph 
Will start a discussion on this issue soon

```python
dataset = DataSet()
# load data from raw text.
dataset.loadCoNLL() 
dataset.preprocess() 
# optional for the data without dev set. This feature should extract the split from preprocess.
train, test=dataset.split() 
dataset.save_to_pickle() 
# load the preprocess data.
dataset.load_from_pickle() 

# codes for model construction
model.fit(train hyperparameter)
model.evaulate(test)
```
